replicaCount: 2

image:
  repository: us-central1-docker.pkg.dev/capstone-mia-1/mad-agents/frontend
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 80

ingress:
  enabled: false
  className: gce
  host: mad-agents.example.com
  path: /
  pathType: Prefix

resources:
  requests: { cpu: 50m, memory: 64Mi }
  limits: { cpu: 200m, memory: 128Mi }
